config/routes.rb
Rails.application.routes.draw do
  # mount Avo::Engine, at: Avo.configuration.root_path

  authenticate :user do
    mount Avo::Engine => "/avo"
  end

  devise_for :users

  namespace :app_tools do
    get "styles/index"
    get "styles/tailwindcss"
  end

  get "home/index"
  root "home#index"

  # resources :pages, only: [:show]

  namespace :app_tools do
    resources :mains, only: [:index]
  end

  get "app_tools", to: "app_tools/mains#index"
  get "tools", to: "app_tools/mains#index"
  get "styles", to: "app_tools/styles#index"

  get "/health_check", to: ->(_) { [200, {}, ["timestamp:#{Time.now.to_i}"]] }

  # if Rails.env.development?
  mount Lookbook::Engine, at: "/lookbook"
  # end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :uuid             not null, primary key
#  admin                  :boolean          default(FALSE)
#  confirmation_sent_at   :datetime
#  confirmation_token     :string
#  confirmed_at           :datetime
#  current_sign_in_at     :datetime
#  current_sign_in_ip     :string
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  failed_attempts        :integer          default(0), not null
#  last_sign_in_at        :datetime
#  last_sign_in_ip        :string
#  locked_at              :datetime
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  sign_in_count          :integer          default(0), not null
#  unconfirmed_email      :string
#  unlock_token           :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_confirmation_token    (confirmation_token) UNIQUE
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#  index_users_on_unlock_token          (unlock_token) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable, :confirmable, :lockable, :trackable, :confirmable

  validates_presence_of :email, :password
end

app/controllers/app_tools/mains_controller.rb
class AppTools::MainsController < ApplicationController
  before_action :authenticate_admin!
  layout "app_tools"

  def index
  end
end

app/controllers/app_tools/styles_controller.rb
class AppTools::StylesController < ApplicationController
  before_action :authenticate_admin!

  layout "app_tools"

  def index
  end

  def tailwindcss
  end
end

app/controllers/application_controller.rb
# :reek:MissingSafeMethod { exclude: [ authenticate_admin! ] }
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :set_page_title

  def authenticate_admin!
    return true if current_user&.admin?
    redirect_to root_path, alert: "You do not have permission to access this page."
  end

  private

  def set_page_title
    @page_title = t(".page_title", default: "").presence || t("#{controller_name}.page_title", default: "").presence || controller_name.titleize
  end
end

app/controllers/avo/users_controller.rb
class Avo::UsersController < Avo::ResourcesController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/app_tools/mains/index.html.erb
<h2>App Tools Home</h2>
<p>Here we have admin dashboards and such.</p>

app/views/app_tools/styles/index.html.erb
<p class="p-6 my-8 mx-0 leading-7 rounded border-2 border-solid border-stone-500 bg-accent-bg text-white">
  <strong class="font-bold text-zinc-300">Are you using Simple.css?</strong>
  <br class="text-zinc-300">
  If you are, it would be great if you considered buying me a coffee to say
  thanks. Things like this really help open source software thrive. You can
  <a href="https://ko-fi.com/kevquirk" class="text-yellow-500 cursor-pointer">Buy Me A Coffee</a>
  or even
  <a href="https://github.com/sponsors/kevquirk" class="text-yellow-500 cursor-pointer">sponsor me on GitHub</a>. ❤️
</p>
<p>
  This page is a demonstration of the elements that can be formatted using
  Simple.css. Each section includes a code block on how to include it in your
  site’s design.
</p>
<p>
  This may be a little basic for some people, but I wanted the barrier for entry
  to be as low as possible for this project.
</p>
<h2>Basic Typography</h2>
<p>
  All the typography of Simple.css uses
  <code>rem</code>
  for sizing. This means that accessibility is maintained for those who change
  their browser font size. The
  <code>body</code>
  element has a size of
  <code>1.15rem</code>
  which makes all the standard font sizes slightly larger. This equates to
  <code>18.4px</code>
  for paragraph text, instead of the standard
  <code>16px</code>.
</p>
<p>
  The heading elements also have an increased top margin in order to break
  blocks of text up better.
</p>
<h1>
  Heading 1
  <code class="text-4xl">3rem</code>
</h1>
<h2>
  Heading 2
  <code class="text-2xl">2.6rem</code>
</h2>
<h3>
  Heading 3
  <code class="text-xl">2rem</code>
</h3>
<h4>
  Heading 4
  <code class="text-lg">1.44rem</code>
</h4>
<h5>
  Heading 5
  <code>1.15rem</code>
</h5>
<h6>
  Heading 6
  <code class="text-xs">0.96rem</code>
</h6>
<div>
  <div>
      <pre><code>&lt;h2&gt;This is a H2 header&lt;h2&gt;
&lt;p&gt;This is some paragraph text.&lt;/p&gt;
</code></pre>
  </div>
</div>
<h3>Links &amp; Buttons</h3>
<p>
  Links are formatted very simply on Simple.css (shock horror). They use the
  <code>accent</code>
  CSS variable and are underlined. There is a
  <code>:hover</code>
  effect that removes the underline.
</p>
<p>
  Buttons use the same
  <code>accent</code>
  CSS variable for their colour. When hovering, there is an opacity effect.
</p>
<p>
  <a href="https://example.com">I’m a hyperlink</a>
</p>
<p>
  <button>I’m a button</button>
</p>
<p>
  <a href="https://example.com">
    <button>I’m a button with a link</button>
  </a>
</p>
<div>
  <div>
      <pre><code>&lt;a href="https://example.com"&gt;I'm a hyperlink&lt;/a&gt;
&lt;button&gt;I'm a button&lt;/button&gt;
&lt;a href="https://example.com"&gt;&lt;button&gt;I'm a button with a link&lt;/button&gt;&lt;/a&gt;
</code></pre>
  </div>
</div>
<h2>Other typography elements</h2>
<p>
  There are a number of other typography elements that you can use with
  Simple.css. Some of the common ones are:
</p>
<ul>
  <li>
    All the standard stuff, like <strong>bold</strong>, <em>italic</em> and
    <u>underlined</u> text.
  </li>
  <li>
    <mark>Highlighting text</mark>
    using the <code>mark</code> element.
  </li>
  <li>Adding <code>inline code</code> using the <code>code</code> element.</li>
  <li>
    Displaying keyboard commands like <kbd>ALT+F4</kbd> using the
    <code>kbd</code> element.
  </li>
</ul>
<div>
  <div>
    <pre><code>&lt;b&gt;Bold text&lt;/b&gt;
&lt;i&gt;Italic text&lt;/i&gt;
&lt;u&gt;Underlined text&lt;/u&gt;
&lt;mark&gt;Highlighted text&lt;/mark&gt;
&lt;code&gt;Inline code&lt;/code&gt;
&lt;kbd&gt;Alt+F4&lt;/kbd&gt;
</code></pre>
  </div>
</div>
<h3>Lists</h3>
<p>We all love a good list, right? I know my wife does!</p>
<ul>
  <li>Item 1</li>
  <li>Item 2</li>
  <li>Item 3</li>
</ul>
<ol>
  <li>Do this thing</li>
  <li>Do that thing</li>
  <li>Do the other thing</li>
</ol>
<div>
  <div>
    <pre><code># Bulleted list
&lt;ul&gt;
  &lt;li&gt;Item 1&lt;/li&gt;
  &lt;li&gt;Item 2&lt;/li&gt;
  &lt;li&gt;Item 3&lt;/li&gt;
&lt;/ul&gt;
# Numbered list
&lt;ol&gt;
  &lt;li&gt;Do this thing&lt;/li&gt;
  &lt;li&gt;Do that thing&lt;/li&gt;
  &lt;li&gt;Do the other thing&lt;/li&gt;
&lt;/ol&gt;
</code></pre>
  </div>
</div>
<h3>Blockquotes</h3>
<p>
  Sometimes you may want to quote someone else in your HTML. For this we use the
  <code>blockquote</code> element. Here’s what a quote looks like with
  Simple.css:
</p>
<blockquote>
  <p>Friends don’t spy; true friendship is about privacy, too.</p>
  <p><cite>– Stephen King</cite></p>
</blockquote>
<div>
  <div>
    <pre><code>&lt;blockquote&gt;
  &lt;p&gt;Friends don’t spy; true friendship is about privacy, too.&lt;/p&gt;
  &lt;p&gt;&lt;cite&gt;– Stephen King&lt;/cite&gt;&lt;/p&gt;
&lt;/blockquote&gt;
</code></pre>
  </div>
</div>
<h3>Code blocks</h3>
<p>
  Code blocks are different from the inline <code>code</code> element. Code
  blocks are used when you want to display a block of code, like this:
</p>
<div>
  <div>
    <pre><code>body {
  color: var(--text);
  background: var(--bg);
  font-size: 1.15rem;
  line-height: 1.5;
  margin: 0;
}
</code></pre>
  </div>
</div>
<div>
  <div>
    <pre><code>&lt;pre&gt;
&lt;code&gt;
  body {
    color: var(--text);
    background: var(--bg);
    font-size: 1.15rem;
    line-height: 1.5;
    margin: 0;
  }
&lt;/code&gt;
&lt;/pre&gt;
</code></pre>
  </div>
</div>
<h2>Navigation</h2>
<p>
  The <code>nav</code> menu is deliberately designed to be extremely simple so
  that you can improve on it as you see fit. Or, just leave it as is to have a
  good looking, functional navigation menu.
</p>
<p>
  There’s no JavaScript or checkbox CSS hacks here. It’s just a collection of
  simple “buttons” that wrap to the given width of the page:
</p>
<nav>
  <a href="">Home</a>
  <a href="">About</a>
  <a href="">Blog</a>
  <a href="">Notes</a>
  <a href="">Contact</a>
</nav>
<p>
  The <code>nav</code> menu will also adapt to smaller screens automatically so
  that it doesn’t take up too much space.
</p>
<p>
  To add a <code>nav</code> menu, just add the following to the
  <code>&lt;header&gt;</code> section of your site:
</p>
<div>
  <div>
    <pre><code>&lt;nav&gt;
  &lt;a href="/"&gt;Home&lt;/a&gt;
  &lt;a href="/about"&gt;About&lt;/a&gt;
  &lt;a href="/blog"&gt;Blog&lt;/a&gt;
  &lt;a href="/notes"&gt;Notes&lt;/a&gt;
  &lt;a href="/guestbook"&gt;Guestbook&lt;/a&gt;
  &lt;a href="/contact"&gt;Contact&lt;/a&gt;
&lt;/nav&gt;
</code></pre>
  </div>
</div>
<h2>Images</h2>
<p>
  In Simple.css, images within the <code>main</code> element are always full
  width and have rounded edges to them. The <code>figcaption</code> element is
  also formatted in Simple.css. Here are examples of images with and without a
  caption:
</p>
<p>
  <img
    src="https://simplecss.org/assets/images/dog-ipad.jpg"
    alt="A dog at an iPad">
</p>
<figure>
  <img
    alt="This is a black swan"
    src="https://simplecss.org/assets/images/goose.jpg">
  <figcaption>This is a black swan</figcaption>
</figure>
<div>
  <div>
    <pre><code># Standard image
&lt;img alt="A dog on an iPad" src="/assets/images/dog-ipad.jpg" /&gt;
# Image with a caption
&lt;figure&gt;
  &lt;img alt="This is a black swan" src="/assets/images/goose.jpg" /&gt;
  &lt;figcaption&gt;This is a black swan&lt;/figcaption&gt;
&lt;/figure&gt;
</code></pre>
  </div>
</div>
<h2>Accordions</h2>
<p>
  Accordions are cool to play with. They’re especially useful when it comes to
  things like FAQ pages. Many people invoke JavaScript, or <code>div</code> for
  life when they use accordions. I don’t really understand why that is when it’s
  available in plain old HTML:
</p>
<details>
  <summary>Spoiler alert!</summary>
  <p>You smell. 🙂</p>
</details>
<div>
  <div>
    <pre><code>&lt;details&gt;
  &lt;summary&gt;Spoiler alert!&lt;/summary&gt;
  &lt;p&gt;You smell. 🙂&lt;/p&gt;
&lt;/details&gt;
</code></pre>
  </div>
</div>
<h2>Tables</h2>
<p>
  Like lists, sometimes you may need to add a table to your webpage. In
  Simple.css tables automatically highlight every other row to make reading
  easier. Table header text is also bold. Here’s what they look like:
</p>
<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Number</th>
  </tr>
  </thead>
  <tbody>
  <tr>
    <td>Jackie</td>
    <td>012345</td>
  </tr>
  <tr>
    <td>Lucy</td>
    <td>112346</td>
  </tr>
  <tr>
    <td>David</td>
    <td>493029</td>
  </tr>
  <tr>
    <td>Kerry</td>
    <td>395499</td>
  </tr>
  <tr>
    <td>Steve</td>
    <td>002458</td>
  </tr>
  </tbody>
</table>
<div>
  <div>
    <pre><code>&lt;table&gt;
  &lt;thead&gt;
    &lt;tr&gt;
      &lt;th&gt;Name&lt;/th&gt;
      &lt;th&gt;Number&lt;/th&gt;
    &lt;/tr&gt;
  &lt;/thead&gt;
  &lt;tbody&gt;
    &lt;tr&gt;
      &lt;td&gt;Jackie&lt;/td&gt;
      &lt;td&gt;012345&lt;/td&gt;
    &lt;/tr&gt;
    &lt;tr&gt;
      &lt;td&gt;Lucy&lt;/td&gt;
      &lt;td&gt;112346&lt;/td&gt;
    &lt;/tr&gt;
    &lt;tr&gt;
      &lt;td&gt;David&lt;/td&gt;
      &lt;td&gt;493029&lt;/td&gt;
    &lt;/tr&gt;
    &lt;tr&gt;
      &lt;td&gt;Kerry&lt;/td&gt;
      &lt;td&gt;395499&lt;/td&gt;
    &lt;/tr&gt;
    &lt;tr&gt;
      &lt;td&gt;Steve&lt;/td&gt;
      &lt;td&gt;002458&lt;/td&gt;
    &lt;/tr&gt;
  &lt;/tbody&gt;
&lt;/table&gt;
</code></pre>
  </div>
</div>
<h2>Forms</h2>
<p>
  Forms are useful for all kinds of things on webpages. Contact forms,
  newsletter sign ups etc. Forms also look pretty good on Simple.css:
</p>
<form>
  <p><strong>This is just a test form. It doesn't do anything.</strong></p>
  <p>
    <select>
      <option selected="selected" value="1">Title</option>
      <option value="2">Mr</option>
      <option value="3">Miss</option>
      <option value="4">Mrs</option>
      <option value="5">Other</option>
    </select>
  </p>
  <p>
    <label>First name</label><br>
    <input type="text" name="first_name">
  </p>
  <p>
    <label>Surname</label><br>
    <input type="text" name="surname">
  </p>
  <p>
    <label>Email</label><br>
    <input type="email" name="email" required="">
  </p>
  <p>
    <label>Enquiry type:</label><br>
    <label><input checked="checked" name="type" type="radio" value="sales">
      Sales</label>
    <br>
    <label><input name="type" type="radio" value="support"> Support</label>
    <br>
    <label><input name="type" type="radio" value="billing"> Billing</label>
  </p>
  <p>
    <label>Message</label><br>
    <textarea rows="6"></textarea>
  </p>
  <p>
    <label for="cars">Choose a car:</label><br>
    <select name="cars" id="cars" multiple="">
      <option value="volvo">Volvo</option>
      <option value="saab">Saab</option>
      <option value="opel">Opel</option>
      <option value="audi">Audi</option>
    </select>
  </p>
  <p>
    <label>
      <input type="checkbox" id="checkbox" value="terms">
      I agree to the <a href="#">terms and conditions</a>
    </label>
  </p>
  <button>Send</button>
  <button type="reset">Reset</button>
  <button disabled="disabled">Disabled</button>
</form>
<pre><code class="language-HTML">
&lt;form&gt;
  &lt;p&gt;&lt;strong&gt;This is just a test form. It doesn't do anything.&lt;/strong&gt;&lt;/p&gt;
  &lt;p&gt;&lt;select&gt;
    &lt;option selected="selected" value="1"&gt;Title&lt;/option&gt;
    &lt;option value="2"&gt;Mr&lt;/option&gt;
    &lt;option value="3"&gt;Miss&lt;/option&gt;
    &lt;option value="4"&gt;Mrs&lt;/option&gt;
    &lt;option value="5"&gt;Other&lt;/option&gt;
  &lt;/select&gt;&lt;/p&gt;
  &lt;p&gt;
  &lt;label&gt;First name&lt;/label&gt;&lt;br&gt;
  &lt;input type="text" name="first_name"&gt;
  &lt;/p&gt;
  &lt;p&gt;
  &lt;label&gt;Surname&lt;/label&gt;&lt;br&gt;
  &lt;input type="text" name="surname"&gt;
  &lt;/p&gt;
  &lt;p&gt;
  &lt;label&gt;Email&lt;/label&gt;&lt;br&gt;
  &lt;input type="email" name="email" required=""&gt;
  &lt;/p&gt;
  &lt;p&gt;
  &lt;label&gt;Enquiry type:&lt;/label&gt;&lt;br&gt;
  &lt;label&gt;&lt;input checked="checked" name="type" type="radio" value="sales" /&gt; Sales&lt;/label&gt; &lt;br /&gt;
  &lt;label&gt;&lt;input name="type" type="radio" value="support" /&gt; Support&lt;/label&gt; &lt;br /&gt;
  &lt;label&gt;&lt;input name="type" type="radio" value="billing" /&gt; Billing&lt;/label&gt;
  &lt;/p&gt;
  &lt;p&gt;
  &lt;label&gt;Message&lt;/label&gt;&lt;br&gt;
  &lt;textarea rows="6"&gt;&lt;/textarea&gt;
  &lt;/p&gt;
  &lt;p&gt;
  &lt;label&gt;
  &lt;input type="checkbox" id="checkbox" value="terms"&gt;
  I agree to the &lt;a href="#"&gt;terms and conditions&lt;/a&gt;
  &lt;/label&gt;
  &lt;/p&gt;
  &lt;button&gt;Send&lt;/button&gt;
  &lt;button type="reset"&gt;Reset&lt;/button&gt;
  &lt;button disabled="disabled"&gt;Disabled&lt;/button&gt;
&lt;/form&gt;
</code></pre>

app/views/home/index.html.erb
<h2>Home</h2>
<p>Landing page stuff goes here...</p>

app/views/layouts/_flash.html.erb
<div id="flash_message" class="relative block mx-auto max-w-lg">
  <% if notice %>
    <p class="rounded-lg bg-green-600 p-3 text-center"><%= notice %></p>
  <% elsif alert %>
    <p class="rounded-lg bg-red-600 p-3 text-center"><%= alert %></p>
  <% end %>
</div>

app/views/layouts/_head.html.erb
<head>
  <title>
    <%= content_for :page_title || "" %> | <%#=  SensibleConfig.app_name %>
  </title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= action_cable_meta_tag %>
  <%= hotwire_livereload_tags if Rails.env.development? %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
</head>

app/views/layouts/app_tools.html.erb
<!DOCTYPE html>
<html>
  <%= render 'layouts/head' %>
  <body>
    <%= render 'shared/app_admin/header' %>
    <main>
      <%= render 'layouts/flash' %>
      <%= yield %>
    </main>
    <%= render 'shared/app_admin/footer' %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= render 'layouts/head' %>
  <body>
    <%= render 'shared/header' %>
    <main>
      <%= render 'layouts/flash' %>
      <%= yield %>
    </main>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/layouts/previews/header.html.erb
<!DOCTYPE html>
<html>
  <%= render 'layouts/head' %>
<header>
  <nav>
    <%= yield %>
  </nav>
</header>
</html>

app/views/shared/_footer.html.erb
<footer class="relative block mx-auto max-w-lg">
  <p>Built with 🤍</p>
</footer>

app/views/shared/_header.html.erb
<header>
  <%= render Sensibles::Header::AppTitleComponent.new %>
  <nav>
    <%# Page.all.each do |page|  %>
    <%# next unless page.visible %>
    <%#= link_to page.title, page_path(page) %>
    <%# end %>
    <%= link_to 'Tools', tools_path %>
    <% if user_signed_in? %>
      <%= button_to "Sign Out", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Sign In", new_user_session_path %>
    <% end %>
  </nav>
</header>

app/views/shared/app_admin/_footer.html.erb
<footer>
  <p>
    Built using and inspired by Simple.css which was created by
    <a href="https://kevq.uk">Kev Quirk</a> and is licensed under the MIT
    license.
  </p>
</footer>

app/views/shared/app_admin/_header.html.erb
<header>
  <h1><%= SensiblesConfig.app_name %></h1>
  <p>
    <%= SensiblesConfig.app_description %>
  </p>
  <nav>
    <%= link_to 'Home', root_path %>
    <%= link_to 'Admin', avo_path, target: '_blank' %>
    <%= link_to 'SimpleCSS', styles_path %>
    <%= link_to 'TailwindCSS', app_tools_styles_tailwindcss_path %>
    <% if Rails.env.development? %>
      <%= link_to 'Lookbook', lookbook_path, target: '_blank' %>
      <%= link_to 'Tailwind Config Viewer', "http://127.0.0.1:3008", target: '_blank' %>
    <% end %>

    <%= link_to "https://github.com/davidteren/sensible_rails_starter", target: "_blank" do %>
      <svg class="icon" viewBox="0 0 32 32">
        <path
          d="M16 0.395c-8.836 0-16 7.163-16 16 0 7.069 4.585 13.067 10.942 15.182 0.8 0.148 1.094-0.347 1.094-0.77 0-0.381-0.015-1.642-0.022-2.979-4.452 0.968-5.391-1.888-5.391-1.888-0.728-1.849-1.776-2.341-1.776-2.341-1.452-0.993 0.11-0.973 0.11-0.973 1.606 0.113 2.452 1.649 2.452 1.649 1.427 2.446 3.743 1.739 4.656 1.33 0.143-1.034 0.558-1.74 1.016-2.14-3.554-0.404-7.29-1.777-7.29-7.907 0-1.747 0.625-3.174 1.649-4.295-0.166-0.403-0.714-2.030 0.155-4.234 0 0 1.344-0.43 4.401 1.64 1.276-0.355 2.645-0.532 4.005-0.539 1.359 0.006 2.729 0.184 4.008 0.539 3.054-2.070 4.395-1.64 4.395-1.64 0.871 2.204 0.323 3.831 0.157 4.234 1.026 1.12 1.647 2.548 1.647 4.295 0 6.145-3.743 7.498-7.306 7.895 0.574 0.497 1.085 1.47 1.085 2.963 0 2.141-0.019 3.864-0.019 4.391 0 0.426 0.288 0.925 1.099 0.768 6.354-2.118 10.933-8.113 10.933-15.18 0-8.837-7.164-16-16-16z"></path>
      </svg>
      GitHub
    <% end %>
  </nav>
</header>